version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: jobfinder-postgres
    environment:
      POSTGRES_USER: jobfinder
      POSTGRES_PASSWORD: jobfinder_dev_password
      POSTGRES_DB: jobfinder_pro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobfinder"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache & Message Broker
  redis:
    image: redis:7-alpine
    container_name: jobfinder-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: jobfinder-api
    environment:
      DATABASE_URL: postgresql://jobfinder:jobfinder_dev_password@postgres:5432/jobfinder_pro
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      SECRET_KEY: dev_secret_key_change_in_production_12345678
      JWT_SECRET_KEY: dev_jwt_secret_change_in_production_12345678
      SESSION_SECRET: dev_session_secret_change_in_production_12345678
      DEBUG: "true"
      LOG_LEVEL: INFO
      FRONTEND_URL: http://localhost:3000
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./api:/app/api
      - ./alembic:/app/alembic
      - ./uploads:/app/uploads
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  # Celery Worker
  celery_worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: jobfinder-celery
    environment:
      DATABASE_URL: postgresql://jobfinder:jobfinder_dev_password@postgres:5432/jobfinder_pro
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      SECRET_KEY: dev_secret_key_change_in_production_12345678
      JWT_SECRET_KEY: dev_jwt_secret_change_in_production_12345678
      LOG_LEVEL: INFO
    depends_on:
      - postgres
      - redis
    volumes:
      - ./api:/app/api
      - ./uploads:/app/uploads
    command: celery -A api.app.celery_app worker --loglevel=info

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    container_name: jobfinder-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

volumes:
  postgres_data:
  redis_data:
